name: Build Watch Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git wget flex bison gperf python3 python3-pip python3-venv \
            cmake ninja-build ccache libffi-dev libssl-dev dfu-util \
            libusb-1.0-0

      - name: Setup ESP-IDF
        shell: bash
        run: |
          # 【修改点1】将分支改为 v5.2.2 以满足 MicroPython 最新源码要求
          git clone -b v5.2.2 --recursive https://github.com/espressif/esp-idf.git
          cd esp-idf
          ./install.sh

      - name: Build mpy-cross
        run: |
          make -C mpy-cross

      - name: Build Firmware
        shell: bash
        run: |
          # 激活 ESP-IDF 环境
          source esp-idf/export.sh
          
          cd ports/esp32
          # 【修改点2】带上 BOARD 参数拉取子模块，避免默认检查 GENERIC 报错
          make BOARD=LYW_WATCH_S3 BOARD_VARIANT=SPIRAM_OCT submodules
          make BOARD=LYW_WATCH_S3 BOARD_VARIANT=SPIRAM_OCT

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware-32mb-nousb
          path: |
            ports/esp32/build-LYW_WATCH_S3-SPIRAM_OCT/firmware.bin
            ports/esp32/build-LYW_WATCH_S3-SPIRAM_OCT/bootloader/bootloader.bin
            ports/esp32/build-LYW_WATCH_S3-SPIRAM_OCT/partition_table/partition-table.bin 
