name: Build Watch Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true  # 必须拉取子模块！

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git wget flex bison gperf python3 python3-pip python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util

    - name: Setup ESP-IDF
      run: |
        # 手动安装 ESP-IDF v5.0.2 (MicroPython 推荐版本)
        git clone -b v5.0.2 --recursive https://github.com/espressif/esp-idf.git
        cd esp-idf
        ./install.sh

    - name: Build mpy-cross
      run: |
        make -C mpy-cross

    - name: Build Firmware
      run: |
        # 加载 IDF 环境
        source esp-idf/export.sh
        
        # 进入 ESP32 目录
        cd ports/esp32
        
        # 编译！
        make BOARD=LYW_WATCH_S3 SUBMODULES=1

    - name: Upload Firmware
      uses: actions/upload-artifact@v4
      with:
        name: firmware-32mb-nousb
        path: ports/esp32/build-LYW_WATCH_S3/firmware.bin
